version: '3'

services:

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: rferreiradev/nginx:prod
    container_name: nginx
    restart: always
    networks:
      - node-nginx-net    
    ports:
      - "80:8080"
    depends_on:
      - nodeserver

  nodeserver:
    build: 
      context: ./node
    container_name: nodeserver
    networks:
      - node-nginx-net
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root      
    networks:      
      - node-nginx-net

networks:
  node-nginx-net:
    driver: bridge